
/*----------------------------------------------------------------------------*/
/* Copyright (c) 2018-2019 FIRST. All Rights Reserved.                        */
/* Open Source Software - may be modified and shared by FRC teams. The code   */
/* must be accompanied by the FIRST BSD license file in the root directory of */
/* the project.                                                               */
/*----------------------------------------------------------------------------*/

package frc.robot.subsystems;


import frc.robot.commands.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.PIDOutput;
import edu.wpi.first.wpilibj.PIDSource;

import com.ctre.phoenix.motorcontrol.ControlMode;
import com.ctre.phoenix.motorcontrol.can.TalonSRX;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */

 //One (1) Rotation of the wheels = 1.57079 feet
 //One 2.5 foot block = 1.59155 rotations
public class BitBoardMotors extends Subsystem {
    private TalonSRX leftMotorOne = new TalonSRX(20); //Left side behind back of hook
    
    private TalonSRX LeftMotorTwo = new TalonSRX(11);
    
    private TalonSRX LeftMotorThree = new TalonSRX(4);

    private TalonSRX RightMotorOne = new TalonSRX(6); //Right side behind back of hook
    
    private TalonSRX RightMotorTwo = new TalonSRX(5);
    
    private TalonSRX RightMotorThree = new TalonSRX(8);

    //public double Power = 0.5;
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
/* private WPI_TalonSRX talonSRX1;
private WPI_TalonSRX talonSRX2;
private WPI_TalonSRX talonSRX3;
*/
    
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public BitBoardMotors() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
/*
talonSRX1 = new WPI_TalonSRX(1);
        
talonSRX2 = new WPI_TalonSRX(2);
        
talonSRX3 = new WPI_TalonSRX(3);
*/
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        setDefaultCommand(new MoveBitBoardMotors());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
    public void move(double Power){
        bitBoardMotorOne.set(ControlMode.PercentOutput, Power);
        bitBoardMotorTwo.set(ControlMode.PercentOutput, Power);
        bitBoardMotorThree.set(ControlMode.PercentOutput, Power);
    }
    @Override
    public void periodic() {
        // Put code here to be run every loop

    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}